name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format Check
        run: python -m black --check src tests

      - name: Run Tests with Coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD/src
          pytest --cov=src --cov-report=html
